mysite/acervo/urls.py
from django.urls import path
from . import views

app_name = 'acervo'
urlpatterns = [
    path('', views.LoginView.as_view(), name = 'login'),
    path('', views.LogoutView.as_view(), name = 'logout'),
    path('cadastro/', views.CadastroView.as_view(), name = 'cadastro'),
    path('home/', views.HomeView.as_view(), name = 'home'),
    path("home/pesquisar", views.PesquisarView.as_view(), name='pesquisa'),

    # urls dos itens

    path('home/salvar/item', views.SaveItemView.as_view(), name='salva_item'),
    path('<int:pk>/editar/item', views.EditarItemView.as_view(), name='item_detalhes'),
    path('<int:pk>/deletar/item', views.DeleteItemView.as_view(), name='deletar_item'),

    # urls dos livros

    path('home/salvar/livro', views.SaveLivroView.as_view(), name='salva_livro'),
    path('<int:pk>/editar/livro', views.EditarLivroView.as_view(), name='livro_detalhes'),
    path('<int:pk>/deletar/livro', views.DeleteLivroView.as_view(), name='deletar_livro'),

    # urls dos contatos

    path('home/salvar/contato', views.SaveContatoView.as_view(), name='salva_contato'),
    path('<int:pk>/editar/contato', views.EditarContatoView.as_view(), name='contato_detalhes'),
    path('<int:pk>/deletar/contato', views.DeleteContatoView.as_view(), name='deletar_contato'),

    # urls dos empréstimos

    path('home/salvar/emprestimo', views.EmprestimoView.as_view(), name='emprestimo'),
    path('<int:pk>/finalizar', views.EmprestimoFinalizarView.as_view(), name='finalizar'),
    path('home/registro', views.RegistroEmprestimoView.as_view(), name='registro_emprestimo'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acervo.urls')),
]

mysite/templates/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Antônio Junior">
    <title>GAP</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins&display=swap">
    {% block 'head' %} {% endblock %}

  </head>
  <body style="position: relative; min-height: 100vh">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'acervo:home' %}">GAP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Adicionar
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                <li><a class="dropdown-item" href="{% url 'acervo:salva_item' %}">Novo item</a></li>
                <li><a class="dropdown-item" href="{% url 'acervo:salva_livro' %}">Novo livro</a></li>
                <li><a class="dropdown-item" href="{% url 'acervo:salva_contato' %}">Novo contato</a></li>
                <li><a class="dropdown-item" href="{% url 'acervo:emprestimo' %}">Novo empréstimo</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'acervo:registro_emprestimo' %}">Registro de devoluções</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'acervo:logout' %}">Sair</a>
            </li>
          </ul>
          <form class="d-flex" method="GET" action="{% url 'acervo:pesquisa' %}">
            <input class="form-control me-2" name="pesquisa" type="search" placeholder="Pesquisar" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Pesquisar</button>
          </form>
        </div>
      </div>
    </nav>

    {% block 'conteudo' %} {% endblock %}

    <div class="footer" style="position: absolute; left: 0; bottom: 0; width: 100%; height: 60px; text-align: center; padding-top: 20px;">
        <h6>Copyright &copy 2023 - Antônio Junior -  Todos os direitos reservados.</h6>
    </div>

  </body>
  <script src="..assets/dist/js/bootstrap.bundle.min.js"></script>
</html>