mysite/acervo/urls.py
from django.urls import path
from . import views

app_name = 'acervo'
urlpatterns = [
    path('', views.LoginView.as_view(), name = 'login'),
    path('', views.LogoutView.as_view(), name = 'logout'),
    path('cadastro/', views.CadastroView.as_view(), name = 'cadastro'),
    path('home/', views.HomeView.as_view(), name = 'home'),
    path("home/pesquisar", views.PesquisarView.as_view(), name='pesquisa'),

    # urls dos itens

    path('home/salvar/item', views.SaveItemView.as_view(), name='salva_item'),
    path('<int:pk>/editar/item', views.EditarItemView.as_view(), name='item_detalhes'),
    path('<int:pk>/deletar/item', views.DeleteItemView.as_view(), name='deletar_item'),

    # urls dos livros

    path('home/salvar/livro', views.SaveLivroView.as_view(), name='salva_livro'),
    path('<int:pk>/editar/livro', views.EditarLivroView.as_view(), name='livro_detalhes'),
    path('<int:pk>/deletar/livro', views.DeleteLivroView.as_view(), name='deletar_livro'),

    # urls dos contatos

    path('home/salvar/contato', views.SaveContatoView.as_view(), name='salva_contato'),
    path('<int:pk>/editar/contato', views.EditarContatoView.as_view(), name='contato_detalhes'),
    path('<int:pk>/deletar/contato', views.DeleteContatoView.as_view(), name='deletar_contato'),

    # urls dos empréstimos

    path('home/salvar/emprestimo', views.EmprestimoView.as_view(), name='emprestimo'),
    path('<int:pk>/finalizar', views.EmprestimoFinalizarView.as_view(), name='finalizar'),
    path('home/registro', views.RegistroEmprestimoView.as_view(), name='registro_emprestimo'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acervo.urls')),
]

mysite/acervo/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User

class Item(models.Model):
    nome = models.CharField(max_length = 50)
    descricao = models.CharField(max_length = 100, blank = True)
    emprestado = models.BooleanField()
    user = models.ForeignKey(User, on_delete = models.CASCADE, default = None)

    def __str__(self):
        return self.nome

class Livro(models.Model):
    titulo = models.CharField(max_length = 100)
    autor = models.CharField(max_length = 50)
    ano = models.IntegerField()
    emprestado = models.BooleanField()
    user = models.ForeignKey(User, on_delete = models.CASCADE, default = None)

    def __str__(self):
       return self.titulo

class Contato(models.Model):
    nome_cont = models.CharField(max_length = 50)
    email = models.CharField(max_length = 50)
    telefone = models.CharField(max_length = 15)
    user = models.ForeignKey(User, on_delete = models.CASCADE, default = None)

    def __str__(self):
        return self.nome_cont

class Emprestimo(models.Model):
    data_emp = models.DateField(default = date.today)
    data_dev = models.DateField(blank = True, null = True)
    item = models.ForeignKey(Item, on_delete = models.CASCADE, null = True, blank = True)
    livro = models.ForeignKey(Livro, on_delete = models.CASCADE, null = True, blank = True)
    contato = models.ForeignKey(Contato, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE, default = None)

    def __str__(self):
        if self.item:
            return f"{self.item.nome}"
        else:
            return f"{self.livro.titulo}"

mysite/acervo/views.py
from django.shortcuts import render, redirect
from django.views import View
from datetime import date
from .models import Item, Livro, Contato, Emprestimo
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# LOGIN E LOGOUT

class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'acervo/login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/home/')
        else:
            contexto = {'erro': 'Usuário ou senha inválidos!'}
            return render(request, 'acervo/login.html', contexto)

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('/')

class CadastroView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'acervo/cadastro.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['senha']
        first_name = request.POST['nome']
        email = request.POST['email']

        if User.objects.filter(username=username).exists():
            contexto = {'erro': 'Este username já existe!'}
            return render(request, 'acervo/cadastro.html', contexto)

        user = User.objects.create_user(username=username, password=password, first_name=first_name, email=email)
        user.save()
        return redirect('/')
    
# HOME E PESQUISAR

@method_decorator(login_required, name='dispatch')
class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        lista_itens = Item.objects.filter(user = user).order_by('nome')
        lista_livros = Livro.objects.filter(user = user).order_by('titulo')
        lista_contatos = Contato.objects.filter(user=user).order_by('nome_cont')
        lista_emp = Emprestimo.objects.filter(user=user, data_dev = None)
        emprestimos_cadastrados = lista_emp.count() > 0
        contexto = {
            'user': user,
            'lista_itens': lista_itens,
            'lista_livros': lista_livros,
            'lista_contatos': lista_contatos,
            'lista_emp': lista_emp,
            'emprestimos_cadastrados': emprestimos_cadastrados,
            }
        return render(request, 'acervo/home.html', contexto)
    
class PesquisarView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        pesquisa = request.GET.get('pesquisa')
        lista_itens = Item.objects.filter(nome__icontains = pesquisa, user = user)
        lista_livros = Livro.objects.filter(titulo__icontains = pesquisa, user = user)
        lista_contatos = Contato.objects.filter(nome_cont__icontains = pesquisa, user = user)
        contexto = {
            'lista_itens': lista_itens,
            'lista_livros': lista_livros,
            'lista_contatos': lista_contatos,
            'pesquisa':pesquisa
            }
        return render(request, 'acervo/pesquisa.html', contexto )
    
# ITEM

class SaveItemView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'acervo/item.html', {'user': request.user})

    def post(self, request, *args, **kwargs):
        nome = request.POST['nome']
        descricao = request.POST['descricao']
        item = Item.objects.create(
            nome = nome,
            descricao = descricao,
            emprestado = False,
            user = request.user
        )
        item.save()
        return redirect('/home/')

class EditarItemView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        item = Item.objects.get(pk = kwargs['pk'])
        return render(request, 'acervo/item_detalhes.html', {'item':item, 'user':user})

    def post(self, request, *args, **kwargs):
        item = Item.objects.get(pk = kwargs['pk'])
        nome = request.POST['nome']
        descricao = request.POST['descricao']

        Item.objects.filter(pk = item.pk).update(nome = nome, descricao = descricao)
        return redirect('/home/')

class DeleteItemView(View):
    def get(self, request, *args, **kwargs):
        item = Item.objects.get(pk = kwargs['pk'])
        item.delete()
        return redirect('/home/')
    
# LIVRO

class SaveLivroView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'acervo/livro.html', {'user':request.user})

    def post(self, request, *args, **kwargs):
        titulo = request.POST['titulo']
        autor = request.POST['autor']
        ano = request.POST['ano']
        livro = Livro.objects.create(
            titulo = titulo,
            autor = autor,
            ano = ano,
            emprestado = False,
            user = request.user
        )
        livro.save()
        return redirect('/home/')

class EditarLivroView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        livro = Livro.objects.get(pk = kwargs['pk'])
        return render(request, 'acervo/livro_detalhes.html', {'livro':livro, 'user':user})

    def post(self, request, *args, **kwargs):
        livro = Livro.objects.get(pk = kwargs['pk'])
        titulo = request.POST['titulo']
        autor = request.POST['autor']
        ano = request.POST['ano']

        Livro.objects.filter(pk = livro.pk).update(titulo = titulo, autor = autor, ano = ano)
        return redirect('/home/')

class DeleteLivroView(View):
    def get(self, request, *args, **kwargs):
        livro = Livro.objects.get(pk = kwargs['pk'])
        livro.delete()
        return redirect('/home/')
    
# CONTATO

class SaveContatoView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'acervo/contato.html', {'user':request.user})

    def post(self, request, *args, **kwargs):
        nome_cont = request.POST['nome_cont']
        email = request.POST['email']
        telefone = request.POST['telefone']
        contato = Contato.objects.create(
            nome_cont = nome_cont,
            email = email,
            telefone = telefone,
            user = request.user
        )
        contato.save()
        return redirect('/home/')

class EditarContatoView(View):
    def get(self, request, *args, **kwargs):
        contato = Contato.objects.get(pk = kwargs['pk'])
        user = request.user
        return render(request, 'acervo/contato_detalhes.html', {'contato':contato, 'user':user})

    def post(self, request, *args, **kwargs):
        contato = Contato.objects.get(pk = kwargs['pk'])
        nome_cont = request.POST['nome_cont']
        email = request.POST['email']
        telefone = request.POST['telefone']

        Contato.objects.filter(pk = contato.pk).update(nome_cont = nome_cont, email = email, telefone = telefone, user = request.user)
        return redirect('/home/')

class DeleteContatoView(View):
    def get(self, request, *args, **kwargs):
        contato = Contato.objects.get(pk = kwargs['pk'])
        contato.delete()
        return redirect('/home/')
    
# EMPRÉSTIMO

class EmprestimoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        lista_itens = Item.objects.filter(user = user).order_by('nome')
        lista_livros = Livro.objects.filter(user = user).order_by('titulo')
        lista_contatos = Contato.objects.filter(user = user).order_by('nome_cont')

        contexto = {
            'lista_itens':lista_itens,
            'lista_livros':lista_livros,
            'lista_contatos':lista_contatos,
            'user':user,
        }
        return render(request, 'acervo/emprestimo.html', contexto)

    def post(self, request, *args, **kwargs):
        item_id = request.POST.get('item')
        livro_id = request.POST.get('livro')
        contato_id = request.POST.get('contato')

        if contato_id:
            contato = Contato.objects.get(id=contato_id)

        with transaction.atomic():
            if item_id == 'Selecionar item':
                item = None
            else:
                item = Item.objects.get(id = item_id)
                item.emprestado = True
                item.save()

            if livro_id == 'Selecionar livro':
                livro = None
            else:
                livro = Livro.objects.get(id = livro_id)
                livro.emprestado = True
                livro.save()

            emp = Emprestimo.objects.create(
                contato = contato,
                livro = livro,
                item = item,
                user = request.user
            )
            emp.save()

            if item:
                item.save()
            if livro:
                livro.save()

        return redirect('/home/')

class EmprestimoFinalizarView(View):
    def get(self, request, *args, **kwargs):
        emp = Emprestimo.objects.get(pk = kwargs['pk'])
        emp.data_dev = date.today()

        livro = emp.livro
        if livro:
            livro.emprestado = False
            livro.save()

        item = emp.item
        if item:
            item.emprestado = False
            item.save()

        emp.save()

        return redirect('/home/')

class RegistroEmprestimoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        lista_emp = Emprestimo.objects.filter(user = user, data_dev__isnull = False)
        emprestimos_finalizados = lista_emp.exists()
        contexto = {'lista_emp': lista_emp, 'user': user, 'emprestimos_finalizados': emprestimos_finalizados}

mysite/acervo/templates/acervo/cadastro.html
{% load static %}

<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'acervo/css/cadastro.css' %}">
  <title>GAP</title>
</head>

<body>

    <div class="cadastro">
        {% if erro %}
            <div class="alert">
                {{ erro }}
            </div>
        {% endif %}

      <div class="container">
        <h1>Cadastre-se</h1>

        <div class="form">
          <form action="{% url 'acervo:cadastro' %}" method="POST"> {% csrf_token %}
            <label>Nome:</label>
            <input type="text" placeholder="Digite o seu nome" name="nome" required />
            <label>Username:</label>
            <input type="text" placeholder="Digite o seu username" name="username" required />
            <label>E-mail:</label>
            <input type="email" placeholder="Digite o seu e-mail" name="email" required />
            <label>Senha:</label>
            <input type="password" placeholder="Digite sua senha" name="senha" required />
            <button type="submit">Cadastrar</button>
          </form>
          <div class="login">
                <a href="{% url 'acervo:login' %}">Já tem uma conta?</a>
          </div>
        </div>
      </div>
    </div>
</body>

</html>

mysite/acervo/templates/acervo/contato.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h4 style="margin-top:30px; margin-bottom:16px">Adicionar novo contato</h4>

    <form action="{% url 'acervo:salva_contato' %}" method="POST"> {% csrf_token %}
        <div class="row g-3">
            <div class="col">
                <input name="nome_cont" type="text" class="form-control" placeholder="Nome" aria-label="Nome">
            </div>
            <div class="col">
                <input name="email" type="text" class="form-control" placeholder="E-mail" aria-label="E-mail">
            </div>
            <div class="col">
                <input name="telefone" type="text" class="form-control" placeholder="Telefone" aria-label="Telefone">
            </div>
        </div>
        <input style="margin-top:30px;" class="btn btn-dark btn-sm" type="submit" value="Salvar">
    </form>

    <hr/>

</main>

{% endblock %}

mysite/acervo/templates/acervo/contato_detalhes.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h4 style="margin-top:30px">Editar contato - {{contato.nome_cont}}</h4>

    <form style="margin-top:30px" action="{% url 'acervo:contato_detalhes' pk=contato.id %}" method="post">{% csrf_token %}
        <div class="row g-3">
            <div class="col">
                <input name="nome_cont" type="text" class="form-control" placeholder="Nome: {{contato.nome_cont}}" aria-label="Nome">
            </div>
            <div class="col">
                <input name="email" type="text" class="form-control" placeholder="E-mail: {{contato.email}}" aria-label="E-mail">
            </div>
            <div class="col">
                <input name="telefone" type="text" class="form-control" placeholder="Telefone: {{contato.telefone}}" aria-label="Telefone">
            </div>
        </div>
        <input style="margin-top:30px" class="btn btn-dark btn-sm"  type="submit" value="Atualizar">
        <a href="/home/"  style="margin-top:30px" class="btn btn-outline-dark btn-sm"> << voltar</a>
    </form>

</main>

{% endblock %}

mysite/acervo/templates/acervo/emprestimo.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h4 style="margin-top:30px; margin-bottom:16px">Adicionar novo empréstimo</h4>

    <form action="{% url 'acervo:emprestimo' %}" method="POST"> {% csrf_token %}
        <div class="row g-3">
            <div class="col">
                <select name="item" class="form-select" aria-label="Default select example">
                  <option selected>Selecionar item</option>
                    {% for item in lista_itens %}
                        {% if item.id %}
                            <option value="{{ item.id }}">{{ item.nome }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <select name="livro" class="form-select" aria-label="Default select example">
                  <option selected>Selecionar livro</option>
                    {% for livro in lista_livros %}
                        {% if livro.id %}
                            <option value="{{ livro.id }}">{{ livro }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <select name="contato" class="form-select" aria-label="Default select example">
                  <option selected>Selecionar contato</option>
                    {% for contato in lista_contatos %}
                        {% if contato.id %}
                            <option value="{{ contato.id }}">{{ contato }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <input style="margin-top:30px;" class="btn btn-dark btn-sm" type="submit" value="Salvar">
    </form>

    <hr/>

</main>

{% endblock %}

mysite/acervo/templates/acervo/item.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h4 style="margin-top:30px; margin-bottom:16px">Adicionar novo item</h4>

    <form action="{% url 'acervo:salva_item' %}" method="POST"> {% csrf_token %}
        <div class="row g-3">
            <div class="col">
                <input name="nome" type="text" class="form-control" placeholder="Nome" aria-label="Nome">
            </div>
            <div class="col">
                <input name="descricao" type="text" class="form-control" placeholder="Descrição" aria-label="Descrição">
            </div>
        </div>
        <input style="margin-top:30px;" class="btn btn-dark btn-sm" type="submit" value="Salvar">
    </form>

    <hr/>

</main>

{% endblock %}

mysite/acervo/templates/acervo/item_detalhes.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h4 style="margin-top:30px">Editar item - {{item.nome}}</h4>

    <form style="margin-top:30px" action="{% url 'acervo:item_detalhes' pk=item.id %}" method="post">{% csrf_token %}
        <div class="row g-3">
            <div class="col">
                <input name="nome" type="text" class="form-control" placeholder="Nome: {{item.nome}}" aria-label="Nome">
            </div>
            <div class="col">
                <input name="descricao" type="text" class="form-control" placeholder="Descrição: {{item.descricao}}" aria-label="Descrição">
            </div>
        </div>
        <input style="margin-top:30px" class="btn btn-dark btn-sm"  type="submit" value="Atualizar">
        <a href="/home/"  style="margin-top:30px" class="btn btn-outline-dark btn-sm"> << voltar</a>
    </form>

</main>

{% endblock %}

mysite/acervo/templates/acervo/livro.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h4 style="margin-top:30px; margin-bottom:16px">Adicionar novo livro</h4>

    <form action="{% url 'acervo:salva_livro' %}" method="POST"> {% csrf_token %}
        <div class="row g-3">
            <div class="col">
                <input name="titulo" type="text" class="form-control" placeholder="Título" aria-label="Título">
            </div>
            <div class="col">
                <input name="autor" type="text" class="form-control" placeholder="Autor" aria-label="Autor">
            </div>
            <div class="col">
                <input name="ano" type="text" class="form-control" placeholder="Ano" aria-label="Ano">
            </div>
        </div>
        <input style="margin-top:30px;" class="btn btn-dark btn-sm" type="submit" value="Salvar">
    </form>

    <hr/>

</main>

{% endblock %}

mysite/acervo/templates/acervo/livro_detalhes.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h4 style="margin-top:30px">Editar livro - {{livro.titulo}}</h4>

    <form style="margin-top:30px" action="{% url 'acervo:livro_detalhes' pk=livro.id %}" method="post">{% csrf_token %}
        <div class="row g-3">
            <div class="col">
                <input name="titulo" type="text" class="form-control" placeholder="Título: {{livro.titulo}}" aria-label="Título">
            </div>
            <div class="col">
                <input name="autor" type="text" class="form-control" placeholder="Autor: {{livro.autor}}" aria-label="Autor">
            </div>
            <div class="col">
                <input name="ano" type="text" class="form-control" placeholder="Ano: {{livro.ano}}" aria-label="Ano">
            </div>
        </div>
        <input style="margin-top:30px" class="btn btn-dark btn-sm"  type="submit" value="Atualizar">
        <a href="/home/"  style="margin-top:30px" class="btn btn-outline-dark btn-sm"> << voltar</a>
    </form>

</main>

{% endblock %}

mysite/acervo/templates/acervo/login.html
{% load static %}

<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'acervo/css/login.css' %}">
  <script src="https://kit.fontawesome.com/cf6fa412bd.js" crossorigin="anonymous"></script>
  <title>GAP</title>
</head>

<body>

    <div class="entrar">
        {% if erro %}
            <div class="alert">
                {{ erro }}
            </div>
        {% endif %}
        <div class="container">
            <h1>Login GAP</h1>
            <div class="form">
                <form method="POST" action="{% url 'acervo:login' %}"> {% csrf_token %}
                    <input name="username" type="text" placeholder="Username" required />
                    <i class="fas fa-user iUser"></i>
                    <input name="password" type="password" placeholder="Senha" required />
                    <i class="fas fa-lock iPassword"></i>
                    <button type="submit">Entrar</button>
                </form>
                <br>
                <div class="cadastro">
                    <h3>Não tem conta?</h3>
                    <a href="{% url 'acervo:cadastro' %}">Cadastre-se</a>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

mysite/acervo/templates/acervo/pesquisa.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h2 style="margin-top:30px; margin-bottom:16px">Resultados para a pesquisa: {{ pesquisa }}</h2>

    {% if lista_itens or lista_livros or lista_contatos %}
        {% if lista_itens %}
            <h4 style="margin-top:30px; margin-bottom:16px">Item</h4>
            <table class="table  table-hover">
                <thead>
                    <tr>
                        <th scope="col">Nome</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Emprestado?</th>
                        <th scope="col">Editar</th>
                        <th scope="col">Deletar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in lista_itens %}
                        <tr>
                            <td> {{ item.nome }} </td>
                            <td> {{ item.descricao }} </td>
                            <td> {% if item.emprestado %} Sim {% else %} Não {% endif %} </td>
                            <td><a href="/{{item.id}}/editar/item"><span class="material-symbols-outlined">edit</span></a></td>
                            <td><a href="/{{item.id}}/deletar/item"><span class="material-symbols-outlined">delete</span></i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}

        {% if lista_livros %}
            <h4 style="margin-top:30px; margin-bottom:16px">Livro</h4>
            <table class="table  table-hover">
                <thead>
                    <tr>
                        <th scope="col">Título</th>
                        <th scope="col">Autor</th>
                        <th scope="col">Ano</th>
                        <th scope="col">Emprestado?</th>
                        <th scope="col">Editar</th>
                        <th scope="col">Deletar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for livro in lista_livros %}
                            <tr>
                                <td> {{ livro.titulo }} </td>
                                <td> {{ livro.autor }} </td>
                                <td> {{ livro.ano }} </td>
                                <td> {% if livro.emprestado %} Sim {% else %} Não {% endif %} </td>
                                <td><a href="/{{livro.id}}/editar/livro"><span class="material-symbols-outlined">edit</span></a></td>
                                <td><a href="/{{livro.id}}/deletar/livro"><span class="material-symbols-outlined">delete</span></i></a></td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}

        {% if lista_contatos %}
            <h4 style="margin-top:30px; margin-bottom:16px">Contato</h4>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Nome</th>
                  <th scope="col">E-mail</th>
                  <th scope="col">Telefone</th>
                  <th scope="col">Editar</th>
                  <th scope="col">Deletar</th>
                </tr>
              </thead>
              <tbody>
                {% for contato in lista_contatos %}
                  <tr>
                    <td> {{ contato.nome_cont }} </td>
                    <td> {{ contato.email }} </td>
                    <td> {{ contato.telefone}} </td>
                    <td><a href="/{{contato.id}}/editar/contato"><span class="material-symbols-outlined">edit</span></a></td>
                    <td><a href="/{{contato.id}}/deletar/contato"><span class="material-symbols-outlined">delete</span></i></a></td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
        {% endif %}
    {% else %}
        <p><strong>Resultado não encontrado.</strong></p>
    {% endif %}

</main>

{% endblock %}

mysite/acervo/templates/acervo/registro_emprestimo.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
<link rel="stylesheet" type="text/css" href="{% static 'acervo/css/base.css' %}">
{% endblock %}

{% block 'conteudo' %}

<main class="container" style="padding-bottom: 80px;">

    <h1 class="title">Devoluções</h1>

    {% if emprestimos_finalizados %}
        <table class="table table-hover">
            <thead>
                <tr>
                  <th scope="col">Nome</th>
                  <th scope="col">Data de empréstimo</th>
                  <th scope="col">Data devolução</th>
                  <th scope="col">Objeto</th>
                </tr>
            </thead>
            <tbody>
                {% for emp in lista_emp %}
                    {% if emp.data_dev %}
                      <tr>
                        <td> {{ emp.contato }} </td>
                        <td> {{ emp.data_emp }} </td>
                        <td> {{ emp.data_dev }} </td>
                        <td> {{ emp }} </td>
                      </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p><strong> Nenhum registro </strong></p>
    {% endif %}

</main>

{% endblock %}